Sprint 25 september
microservices-course-itmo/winelab-parser-service pull request #3
Opened 2020-09-29 17:20 UTC by danonya666

2020-09-30 12:27 UTC, shinehlina requested changes

2020-09-30 12:27 UTC, shinehlina commented on pom.xml
> +            <version>1.13.1</version>
Возьмите последний pom из demo-service (он с нашим парентом и без плагинов)
Вынесите в проперти версию, как остальные
Апните версию самого приложения

2020-09-30 12:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +    MessageRepository messageRepository;
Это IDEA не подчеркивает, как нерекомендуемый способ автовайринга?
Модификатор доступа. Кажется, может быть private

2020-09-30 12:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +            final String patternAlcoholPercentage = "\\d{0,2}([.,]\\d+)? ?%";
Воу, вот это мастерское обращение с регулярками!

2020-09-30 12:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +            ex.printStackTrace();
Сделайте через логер. Мы потом же будем логи показывать в кибане)

2020-09-30 12:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +                Integer price = (int) (Double.parseDouble(element.select("span").get(1).ownText().replaceAll(" ", "")) * 100);
Лучше примитивы юзать почти всегда

2020-09-30 12:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +                Integer id = Integer.parseInt(idStr);
Тоже примитивы

2020-09-30 12:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +            ex.printStackTrace();
Тоже log

2020-09-30 12:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +    public void setBrand(String brand) {
У вас есть `@Setter`. Ломбок сгенерит все для вас, удалите все сеттеры

2020-09-30 12:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +        return "Wine{" +
Насколько я вижу, вы просто выводите все поля, так что возьмите `@ToString` ломбока.

2020-09-30 13:39 UTC, shinehlina commented
У вас еще ингда форматирование слетает. В идее - ctrl + alt + L. Для импортов - ctrl + alt+ O. Или можно настроить при коммите

2020-10-06 17:12 UTC, Anglopol requested changes

2020-10-06 17:12 UTC, Anglopol commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +    public void parseProductPage(@RequestParam int productID) {
Как-то нехорошо, что у вас так много всего делается в контроллере, вынесите, пожалуйста, логику в сервис

2020-10-06 17:12 UTC, Anglopol commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +            Elements elementsWithId = document.select("a.product_card.js-product-click");
Вынесите в константы хардкод

2020-10-06 17:12 UTC, Anglopol commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +        final String url = "https://www.winelab.ru/";
В проперти перенесите

2020-10-06 17:12 UTC, Anglopol commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +            Elements elementsWithId = document.select("a.product_card.js-product-click");
Касается не только этой строки

2020-10-06 17:12 UTC, Anglopol commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +
Лишние пропуски

2020-10-06 17:12 UTC, Anglopol commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +
Уберите везде

2020-10-06 17:12 UTC, Anglopol commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +
Добавьте доку

2020-10-06 17:12 UTC, Anglopol commented on pom.xml
>          <postgres.driver.version>42.2.14</postgres.driver.version>
Обновите помник

2020-10-06 17:12 UTC, Anglopol commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +@Data
Не используйте дату, она генерит Equals and HashCode по изменяемым полям, который вам не нужен

2020-10-07 18:46 UTC, somov7 commented on pom.xml
> +            <version>1.13.1</version>
Я не понимаю чего тут конкретно от меня хотят помогите :((( (репозитория demo-service я тоже не могу найти, хотя мне казалось, что раньше я его находил)

2020-10-07 19:32 UTC, shinehlina requested changes
А зачем вы разрезолвили конверсейшены? Особенно которые не поправили
Плюс мы сами буднм их резолвить. Если вам нужно как-то отметить, что вы сделали - напишите "fixed"/"done"/"ок"

2020-10-07 19:32 UTC, shinehlina commented on pom.xml
>          <postgres.driver.version>42.2.14</postgres.driver.version>
Последний из demo-service

2020-10-07 19:32 UTC, shinehlina commented on pom.xml
>          <current-version>0.1.0</current-version>
Версию ап

2020-10-07 19:32 UTC, shinehlina commented on pom.xml
> +        <!--        TODO create-service: replace-->
Ну и todo убрать

2020-10-07 20:05 UTC, somov7 commented on pom.xml
> +        <!--        TODO create-service: replace-->
> 
> 
> А зачем вы разрезолвили конверсейшены? Особенно которые не поправили
> Плюс мы сами буднм их резолвить. Если вам нужно как-то отметить, что вы сделали - напишите "fixed"/"done"/"ок"

Ну, во-первых, я отмечал только то, что пофиксил, а во-вторых, не знал, что резолвы не для этого нужны, извините.

2020-10-07 21:14 UTC, shinehlina commented on pom.xml
> +    <!--    TODO create-service: rename artifact-->
todo можно и убрать)

2020-10-07 21:14 UTC, shinehlina commented on pom.xml
> +            <version>${jsoup.version}</version>
О, хорошо, что все-таки нашли) А то я только сейчас заметила, что были проблемы

2020-10-07 21:14 UTC, shinehlina commented on pom.xml
> +        <!--        TODO create-service: replace-->
Видимо, ты в тот момент не запушил еще. Я только видела, что попросили добавить модификатор доступа, он не добавлен, но помечен резолвленным)

Норм, в следующий раз знать будете)

2020-10-07 21:27 UTC, shinehlina requested changes
Как исправите странное обращение с исключениями и todo уберете, то будет апрув)

2020-10-07 21:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +    //Price in cents
Забавно, центы? Или это было копейками... В любом случае для этого спринта норм, все равно в кафку будете отправлять классы общего апи)

2020-10-07 21:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +            return null;
Может, лучше логировать такое?)
Если вы вдруг считаете, что такого никогда не будет (если я правильно понимаю, то это не тот случай), то нужно это объяснить комментарием

2020-10-07 21:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +            return null;
Также

2020-10-07 21:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +                isLastPage = true;
Здесь тоже нужно что-нибудь, что объяснит это исключение

2020-10-07 21:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +
Я так понимаю, это никуда не делось:(

2020-10-08 06:46 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +
Пытаюсь понять, что не так с этими местом. Пустая строчка между пакетом и импортами? Если что, сама IDEA их так и отформатировала

2020-10-08 11:23 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +
Не, между самими импортами

2020-10-08 11:23 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +
Ну ладно, ок

2020-10-08 11:24 UTC, shinehlina approved these changes

2020-10-09 12:51 UTC, Anglopol approved these changes

2020-10-09 13:39 UTC, merged