Sprint 3
microservices-course-itmo/winelab-parser-service pull request #4
Opened 2020-10-13 16:23 UTC by danonya666

2020-10-16 19:24 UTC, shinehlina requested changes
Я не смотрела до конца. Вы же не используете api парсеров общее.. Вам же нужно использовать эти классы (https://github.com/microservices-course-itmo/parser-common-api). Если есть вопросы - можете в телеге написать

2020-10-16 19:24 UTC, shinehlina commented on pom.xml
> +        <dependency>
Вам же уже это не нужно)

2020-10-16 19:24 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/api/WineLabServiceApiProperties.java
> +// (powered by FernFlower decompiler)
?

2020-10-16 19:24 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/api/WineLabServiceApiProperties.java
> +@ConfigurationProperties(
Вам это не нужно. Во-первых, тут почему-то demo-service написано
Во-вторых, это должно в api лежать
В-третьих, у вас есть общепарсеровные проперти. Вам нужно только знать, куда отправлять ивент. Это есть в common parser api

2020-10-16 19:24 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/configuration/KafkaConfiguration.java
> +    BaseKafkaHandler<Wine> wineTopicMessagesHandler(Properties consumerProperties,
Вам не нужно читать сообщения из кафки же)

2020-10-16 19:24 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/KafkaController.java
> +    public KafkaController(KafkaMessageSender<Wine> kafkaSendMessageService) {
Я все-таки не понимаю, вы же кладете в кафку свое какое-то dto, а не общее

2020-10-16 19:24 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/configuration/KafkaConfiguration.java
> +                                                         WineLabServiceApiProperties wineLabServiceApiProperties,
должны быть ParserCommonApiProperties (или как там оно называется)

2020-10-16 19:24 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
>              log.error(ex.getMessage());
Возможно, лучше логировать полностью. Так вы это делаете без stackTrace. И добавьте еще какое-то описание, чтобы было понятно
`log.error("Error while parsing wine with id {}", prodictId, ex)`

2020-10-16 19:24 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +        } catch (IOException ex) {
То же самое

2020-10-16 19:24 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/ApiWine.java
> +public class ApiWine {
Что это такое?)

2020-10-16 19:24 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/job/UpdateWineLabJob.java
> +        log.info("end UpdateWineLabJob run job method at " + new Date().getTime() + " duration = " + (new Date().getTime() - startDate));
Используйте синтаксик, как я приводила выше 
log.error("Error while parsing wine with id {}", prodictId, ex)

2020-10-19 20:13 UTC, Chank1e commented on src/main/java/com/wine/to/up/winelab/parser/service/api/WineLabServiceApiProperties.java
> +// (powered by FernFlower decompiler)
Исправлено

2020-10-19 20:14 UTC, Chank1e commented on src/main/java/com/wine/to/up/winelab/parser/service/api/WineLabServiceApiProperties.java
> +@ConfigurationProperties(
Исправлено

2020-10-19 20:14 UTC, Chank1e commented on src/main/java/com/wine/to/up/winelab/parser/service/configuration/KafkaConfiguration.java
> +    BaseKafkaHandler<Wine> wineTopicMessagesHandler(Properties consumerProperties,
Исправлено

2020-10-19 20:14 UTC, Chank1e commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/KafkaController.java
> +    public KafkaController(KafkaMessageSender<Wine> kafkaSendMessageService) {
Исправлено

2020-10-19 20:14 UTC, Chank1e commented on src/main/java/com/wine/to/up/winelab/parser/service/configuration/KafkaConfiguration.java
> +                                                         WineLabServiceApiProperties wineLabServiceApiProperties,
Исправлено

2020-10-19 20:14 UTC, Chank1e commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/ApiWine.java
> +public class ApiWine {
Удалил

2020-10-19 20:15 UTC, Chank1e commented on src/main/java/com/wine/to/up/winelab/parser/service/job/UpdateWineLabJob.java
> +        log.info("end UpdateWineLabJob run job method at " + new Date().getTime() + " duration = " + (new Date().getTime() - startDate));
Исправлено!

2020-10-21 17:39 UTC, shinehlina requested changes

2020-10-21 17:39 UTC, shinehlina commented on pom.xml
> +<groupId>com.wine.to.up</groupId>
Форматирование полетело

2020-10-21 17:39 UTC, shinehlina commented on pom.xml
> +    <dependency>
Он вам не нужен

2020-10-21 17:39 UTC, shinehlina commented on pom.xml
> +            <groupId>junit</groupId>
Эта зависимость уже есть

2020-10-21 17:39 UTC, shinehlina commented on pom.xml
> +            <artifactId>hamcrest-core</artifactId>
Эта тоже, скорее всего

2020-10-21 17:39 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/configuration/GeneralPurposesBeansConfig.java
> +import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
Импорты доавились, а новый код - нет. Наверное, они лишние

2020-10-21 17:39 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
>              log.error(ex.getMessage());
?

2020-10-21 17:39 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/messaging/serialization/EventDeserializer.java
> +public class EventDeserializer implements Deserializer<Wine> {
Это же ваше вино

2020-10-21 17:39 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +                    System.out.println(name);
Логгер

2020-10-26 15:42 UTC, shinehlina requested changes
Короче уберите зависимость и апрув поставлю. Остальное сделайте, пожалуйста, в след пр

2020-10-26 15:42 UTC, shinehlina commented on pom.xml
> +        <dependency>
Не убрали)

2020-10-26 15:42 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +        ParserApi.Wine.Sugar sugar =
Добавьте просто в сам ваш Sugar поле ParserApi.Wine.Sugar, которое ему соответсвует.
Вот это выглядит не оч)

2020-10-26 15:42 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +                        : instanceColor == Color.WHITE
С этим то же самое

2020-10-26 15:42 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +    public ParserApi.Wine toParserWine() {
Так, это все легко делается ModelMapper. Он уже есть в проекте. Он смотрит, и сеттит одинакове поля. Почитайте и следайте в след спринте

2020-10-30 10:07 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +    public ParserApi.Wine toParserWine() {
А можно без этого обойтись? Про встроенный в интернете ничего нет, я вообще не уверен, что он для этого предназначен, а org.modelmapper не умеет маппить в final классы (а в ParserApi как раз такие)

2020-11-01 12:07 UTC, shinehlina commented on src/main/java/com/wine/to/up/winelab/parser/service/dto/Wine.java
> +    public ParserApi.Wine toParserWine() {
"Встроенны" - это и есть org.modelmapper. Ты говоришь о иммутабельных класса? Вообще можно настроить) Просто вы поля с одними именами по факту ставите. Рекомендуемый способ для такого - modelmapper

2020-11-01 12:08 UTC, shinehlina approved these changes

2020-11-03 17:05 UTC, merged