Sprints 3 6 merge
microservices-course-itmo/winelab-parser-service pull request #6
Opened 2020-11-13 15:42 UTC by somov7

2020-11-14 15:26 UTC, 4ound requested changes
Еще в целом по тестам хотелось написать, что testThrow и testNotThrow не самым лучшим образом тестируют ваш код

если вы будете обрабатывать try/catch в месте его возникновения, будет намного лучше

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/UpdateService.java
> +    @Autowired
было бы хорошо вынести это в конфигурации, вместо использования autowired
(относится ко всем местам, а не только в этом классе)

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/UpdateService.java
> +            log.error("Update catalog error, {}", e.toString());
тут нужно написать log.error("Update catalog error, ", e); (в текущем варианте не напишется stacktrace)
(относится ко всем местам)

2020-11-14 15:26 UTC, 4ound commented on src/main/resources/application.properties
> +parser.protocolPrefix=https://
может быть лучше вынести свойста парсинга в отдельный файл
это все же не application.properties

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +    public Map<Integer, Wine> parseCatalogs() throws IOException {
мне кажется, что лучше отлавливать все ошибки как только они возникают, а не пробрасывать их чуть ли не в самое начало
(относится ко всем местам в коде)

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +            parseCatalog(catalog, wines);
все, конечно, работает
но может быть лучше выстроить логику так, что метод либо получает вино и складывает в мапу, либо генерит мапу полностью сам

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/job/ParseJob.java
> +
пустые строчки не круто!
(относится ко всему коду)

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +        final String sparklingCategory = "Шампанские и игристые вина";
было бы хорошо, вынести это в константы
(относится ко всему коду)

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +        String name = document.selectFirst(nameSelector).ownText();
было бы хорошо проверить, что name появился, не будет ли NPE при вызове ownText()?

вообще, если не получилось взять name (и еще некоторые ключевые параметры), может быть логично не создавать вообще такое вино?

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +            BigDecimal newPrice = new BigDecimal(newPriceString);
вам правда нужна такая точность, что float не подойдет?)

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +                (wine.getAlcoholContent() != null ? "%3AAlcoholContent%3A%255B" + wine.getAlcoholContent() + "%2BTO%2B" + wine.getAlcoholContent() + "%255D" : "") +
давайте здесь сделаем StringBuilder/StringFormat и сами параметры вынесем в константы.
Может быть вообще генерировать url с какой-то либой, чтобы не писать %3A

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +            assert cards.size() == 1 && Integer.parseInt(cards.first().attr(idSelector)) == productID;
тут точно нужен assert, а не if/return

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +    private ParserApi.Wine.Color getColor(String color) {
Почитай как сделать Enum с resolve, лучше переписать так.

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +        final Map<String, String> countries = Map.of(
давай тоже в константы вынесем (а может быть даже в проперти)
(ко всем похожим методам относится)

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +            for (Element tagEl : tags) {
выглядит грустно(

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +                                count.set(count.get() + 1);
у AtomicInteger есть метод incrementAndGet()

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +        return Arrays.stream(wineStrings).reduce(false,
правда ли здесь нужна такая сложная логика и set.contains(name) не подойдет?
(относится ко всему коду)

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/KafkaService.java
> +    void sendWine(Wine wine) {
лучше отправлять вина не по одному, а каким-то батчем

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/KafkaService.java
> +    void sendWine(Wine wine) {
а еще я не вижу, где у вас формируется Protobuf

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/services/KafkaService.java
> +public class KafkaService {
вы, видимо, еще не доделали этот класс, верно?

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/api/WineLabServiceApiProperties.java
> +public class WineLabServiceApiProperties {
используйте property файл из parser common api

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +            log.error(ex.getMessage());
писать только message без stacktrace не оч хорошо
(относится ко всему коду)

2020-11-14 15:26 UTC, 4ound commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +public class ParserController {
возможно, вам было бы удобнее возвращать json с распаршенными винами на страницу (как ответ)
(конвертацию в json писать самим не нужно, просто изменить тип у методов, например List<Wine>)

2020-11-14 15:26 UTC, 4ound commented on src/test/java/com/wine/to/up/winelab/parser/service/controller/ControllerTest.java
> +            mockMvc.perform(get("/parser/catalogs"));
а если вдруг выполнится try, может быть стоит сделать Assert внутри этого блока?
(относится ко всему коду)

2020-11-14 15:26 UTC, 4ound commented on src/test/java/com/wine/to/up/winelab/parser/service/dto/WineTest.java
> +            Wine wine = parserService.parseProduct(1014769);
не очень хороший тест - как только вино удалят с сайта или сменится id он упадет
(относится ко всему коду)

2020-11-14 15:26 UTC, 4ound commented on src/test/java/com/wine/to/up/winelab/parser/service/dto/WineTest.java
> +            Wine wine = parserService.parseProduct(1014769);
советую парсить N вин и проверять, что nameCounter или imageCounter > 0

2020-11-14 15:26 UTC, 4ound commented on src/test/java/com/wine/to/up/winelab/parser/service/dto/WineTest.java
> +            Assertions.assertEquals((float) 1243.0, apiWine.getOldPrice());
напиши 1234.0f
(относится ко всему коду)

2020-11-14 15:26 UTC, 4ound commented on src/test/java/com/wine/to/up/winelab/parser/service/services/ParserServiceTest.java
> +    public void testParsedValuesEqualExpected() {
мне кажется или WineTest выглядит ровно также

2020-11-14 15:26 UTC, 4ound commented on src/test/java/com/wine/to/up/winelab/parser/service/services/ParserServiceTest.java
> +    public void testParsedValuesEqualExpected() {
для чего вообще был написан WineTest (в нем же нет никакой бизнес-логики)
если хотитие проверить, что вино корректно распарсилось (сравнить поля), сохраните куда-нибудь html файл и замокайте parserService.parseProduct() возвращать его контент

2020-11-18 17:23 UTC, 4ound commented
а еще было бы хорошо иметь эндпойнты для того, чтобы можно было инициировать парсинг вручную
(кажется нашу команду просили сделать 2: один парсит и дает на выходе json, а второй запускает обычный процесс парсинга)
потом еще один эндпойнт просила сделать команда ML, которая бы возвращала данные в csv

2020-11-22 11:51 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +            parseCatalog(catalog, wines);
Там прикол в том, что айдишники в разных каталогах могли пересекаться, и это сделано, чтоб вино два раза не парсилось

2020-11-22 12:40 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/KafkaService.java
> +    void sendWine(Wine wine) {
[Вот этот коммит](https://github.com/microservices-course-itmo/winelab-parser-service/commit/84584caa1229b7b46edc85c8e67e0fa2f40a1ebf)

2020-11-22 12:42 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +        return Arrays.stream(wineStrings).reduce(false,
Так в нейме много слов, например, что-то типа "Вино Legende Domaine Barons de Rothschild Pauillac красное сухое 0,75 л"

2020-11-22 13:33 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/UpdateService.java
> +            log.error("Update catalog error, {}", e.toString());
[Вот](https://github.com/microservices-course-itmo/winelab-parser-service/commit/1639e14acb783742b7b258bacf474309f73e76e5)

2020-11-22 13:33 UTC, somov7 commented on src/main/resources/application.properties
> +parser.protocolPrefix=https://
[Вот](https://github.com/microservices-course-itmo/winelab-parser-service/commit/2816b537334349928ea994263a3b1bc1fab6f772)

2020-11-22 14:30 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +public class ParserController {
[Допустим](https://github.com/microservices-course-itmo/winelab-parser-service/commit/3c15eb1ddc5788fa4a67ac5fb37b85d7da33b203)

2020-11-22 14:33 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +            BigDecimal newPrice = new BigDecimal(newPriceString);
Со слов Игоря float зло + проверку на null хочется делать кое-где

2020-11-22 14:34 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +    private ParserApi.Wine.Color getColor(String color) {
А зачем, если и так норм работает? Мы пробовали свои конвертировать, оказалось, что сразу апишные писать проще всего

2020-11-22 14:35 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/UpdateService.java
> +    @Autowired
[Вот](https://github.com/microservices-course-itmo/winelab-parser-service/commit/c85b822d50c923cd3fff0763fd9ce7e22e6208ce)

2020-11-25 05:10 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +        final String sparklingCategory = "Шампанские и игристые вина";
[Вынес в проперти](https://github.com/microservices-course-itmo/winelab-parser-service/commit/04a71f733ad0ee68cd194dcdad1eb52be8fefe4b)

2020-11-25 05:10 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +                (wine.getAlcoholContent() != null ? "%3AAlcoholContent%3A%255B" + wine.getAlcoholContent() + "%2BTO%2B" + wine.getAlcoholContent() + "%255D" : "") +
[Тут](https://github.com/microservices-course-itmo/winelab-parser-service/commit/04a71f733ad0ee68cd194dcdad1eb52be8fefe4b)

2020-11-25 05:12 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +                                count.set(count.get() + 1);
Сделано

2020-11-25 05:13 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/KafkaService.java
> +public class KafkaService {
Да нет, просто с древних времён лежит бесполезный тестовый класс

2020-11-25 05:17 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/controller/ParserController.java
> +            log.error(ex.getMessage());
Сделано

2020-12-01 16:58 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +    public Map<Integer, Wine> parseCatalogs() throws IOException {
Сделано

2020-12-02 09:36 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +        String name = document.selectFirst(nameSelector).ownText();
Больше не возвращаем вино без названия или цены
![image](https://user-images.githubusercontent.com/39019505/100855165-f120d200-349a-11eb-8b9f-42fc901d39ce.png)

2020-12-02 12:07 UTC, somov7 commented on src/main/java/com/wine/to/up/winelab/parser/service/services/ParserService.java
> +            assert cards.size() == 1 && Integer.parseInt(cards.first().attr(idSelector)) == productID;
[Убрали ассершн](https://github.com/microservices-course-itmo/winelab-parser-service/commit/84a7e84942280ebd1f9deb35d5aa542f3e1080ce)

2020-12-05 00:15 UTC, 4ound approved these changes

2020-12-05 14:05 UTC, merged